### ISSUE TITLE
Configure/provision S3 buckets of type nas

### ISSUE THREAD

**Issue by freedge** [ansible-collections/netapp.ontap#153]
### Summary

ONTAP 9.12.1 supports S3 buckets with type=nas. It would be nice if the collection would support

- creating the bucket of type nas:
```
vserver object-store-server bucket create -type nas -vserver vs -bucket mybucket -nas-path /myvol
```
- creating the user mapping:
```
vserver name-mapping create -position 1 -direction s3-unix -vserver vs -pattern user -replacement me
vserver name-mapping create -position 1 -direction s3-win -vserver vs -pattern user -replacement TEST1\\tata
```

### Component Name

netapp.ontap.na_ontap_name_mappings

### Additional Information

```yaml (paste below)

```

**Comment by mohanrajb9** [comment]
tracked internally with DEVOPS-6193.

**Comment by carchi8py** [comment]
This was fixed as part of 22.6.0

**Comment by freedge** [comment]
netapp.ontap.na_ontap_name_mappings

is not changed so the name mapping cannot be done for s3_unix and s3_win.

type=nas was added but  -nas-path option is not present. I don't think this is fixed

**Comment by mohanrajb9** [comment]
sorry, we will add the choices` s3_unix, s3_win`  to direction option in na_ontap_name_mappings module. Thanks.

**Comment by freedge** [comment]
thanks. Without nas-path it's impossible to use type=nas, the module fails with
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [nasim01a -> localhost]: FAILED! => {"changed": false, "msg": "Error creating S3 bucket myvol: calling: protocols/s3/buckets: got {'message': 'Parameter \"nas_path\" must be present for creating \"nas\" bucket.', 'code': '92406026'}."}
```
